language: objective-c
osx_image: xcode9
before_script: ./pkg u
script: xcodebuild test -scheme apollo-fetcher-Package -enableCodeCoverage YES
after_success:
  - bash <(curl -s https://codecov.io/bash) -t 06e92d68-0f62-46e2-9356-7bb3ed6edc8e
