language: objective-c
osx_image: xcode10.2
before_script:
  - swift package update
  - swift package generate-xcodeproj --xcconfig-overrides Config.xcconfig
script:
  - set -o pipefail && xcodebuild test -enableCodeCoverage YES -scheme sqlite-helper-Package ONLY_ACTIVE_ARCH=NO | xcpretty
after_success:
  - bash <(curl -s https://codecov.io/bash) -t adf621f8-0bf8-4006-a715-05707f95658a
